<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>cn.ncepu</groupId>
    <artifactId>advanced-language-programming-learning</artifactId>
    <packaging>pom</packaging>
    <version>1.0-SNAPSHOT</version>

    <modules>
        <module>alpl-common</module>
        <module>alpl-main</module>
        <module>alpl-mbg</module>
        <module>alpl-security</module>
    </modules>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>

        <log4j.version>1.2.17</log4j.version>
        <lombok.version>1.16.18</lombok.version>
        <slf4j.version>1.7.25</slf4j.version>
        <hutool.version>5.4.0</hutool.version>

        <spring.boot.dependencies>2.2.2.RELEASE</spring.boot.dependencies>
        <druid.version>1.1.16</druid.version>
        <mybatis.plus.version>3.3.2</mybatis.plus.version>

        <jedis.version>2.7.1</jedis.version>
        <rabbitmq.version>5.12.0</rabbitmq.version>
        <test.version>2.2.2.RELEASE</test.version>
        <junit.version>4.12</junit.version>
        <jjwt.version>0.9.0</jjwt.version>
        <nimbus-jose-jwt.version>8.16</nimbus-jose-jwt.version>
        <pagehelper-starter>1.3.0</pagehelper-starter>
        <mybatis-generator.version>1.4.0</mybatis-generator.version>
        <mybatis-dynamic-sql.version>1.4.0</mybatis-dynamic-sql.version>

        <alpl-common.version>1.0-SNAPSHOT</alpl-common.version>
        <alpl-mbg.version>1.0-SNAPSHOT</alpl-mbg.version>
        <alpl-security.version>1.0-SNAPSHOT</alpl-security.version>

        <mysql-connector-java.version>5.1.47</mysql-connector-java.version>
        <mybatis.version>3.5.5</mybatis.version>
        <spring-data-commons.version>2.2.2.RELEASE</spring-data-commons.version>
        <minio.version>7.1.0</minio.version>
        <poi.version>4.1.2</poi.version>
        <poi-ooxml.version>4.1.2</poi-ooxml.version>
    </properties>

        <!--        子模块可能用到的依赖  -->

        <!--        <dependency>-->
        <!--            <groupId>org.springframework.boot</groupId>-->
        <!--            <artifactId>spring-boot-starter-web</artifactId>-->
        <!--        </dependency>-->

        <!--        &lt;!&ndash; spring-security &ndash;&gt;-->
        <!--        <dependency>-->
        <!--            <groupId>org.springframework.boot</groupId>-->
        <!--            <artifactId>spring-boot-starter-security</artifactId>-->
        <!--        </dependency>-->

        <!--        &lt;!&ndash; spring-redis &ndash;&gt;-->
        <!--        <dependency>-->
        <!--            <groupId>org.springframework.boot</groupId>-->
        <!--            <artifactId>spring-boot-starter-data-redis</artifactId>-->
        <!--        </dependency>-->

    <dependencies>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
            <exclusions>
                <exclusion>
                    <artifactId>slf4j-api</artifactId>
                    <groupId>org.slf4j</groupId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>cn.hutool</groupId>
            <artifactId>hutool-all</artifactId>
            <version>${hutool.version}</version>
        </dependency>

        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-configuration-processor</artifactId>
            <optional>true</optional>
        </dependency>

        <!--log4j -->
        <dependency>
            <groupId>log4j</groupId>
            <artifactId>log4j</artifactId>
            <version>${log4j.version}</version>
        </dependency>

        <!--slf4j-->
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>${slf4j.version}</version>
        </dependency>

        <!--test-->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <artifactId>slf4j-api</artifactId>
                    <groupId>org.slf4j</groupId>
                </exclusion>
            </exclusions>
        </dependency>

        <!--        &lt;!&ndash;devtools&ndash;&gt;-->
        <!--        <dependency>-->
        <!--            <groupId>org.springframework.boot</groupId>-->
        <!--            <artifactId>spring-boot-devtools</artifactId>-->
        <!--            <scope>runtime</scope>-->
        <!--            <optional>true</optional>-->
        <!--        </dependency>-->

    </dependencies>


    <dependencyManagement>
        <dependencies>

            <dependency>
                <groupId>cn.ncepu</groupId>
                <artifactId>alpl-common</artifactId>
                <version>${alpl-common.version}</version>
            </dependency>

            <dependency>
                <groupId>cn.ncepu</groupId>
                <artifactId>alpl-mbg</artifactId>
                <version>${alpl-mbg.version}</version>
            </dependency>

            <dependency>
                <groupId>cn.ncepu</groupId>
                <artifactId>alpl-security</artifactId>
                <version>${alpl-security.version}</version>
            </dependency>

            <!--Spring Boot 2.2.2-->
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring.boot.dependencies}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <!--SpringData工具包-->
            <dependency>
                <groupId>org.springframework.data</groupId>
                <artifactId>spring-data-commons</artifactId>
                <version>${spring-data-commons.version}</version>
            </dependency>

            <!-- Mybatis -->
            <dependency>
                <groupId>org.mybatis</groupId>
                <artifactId>mybatis</artifactId>
                <version>${mybatis.version}</version>
            </dependency>

            <!-- MySQL Connector -->
            <dependency>
                <groupId>mysql</groupId>
                <artifactId>mysql-connector-java</artifactId>
                <version>${mysql-connector-java.version}</version>
            </dependency>

            <!-- Druid -->
            <dependency>
                <groupId>com.alibaba</groupId>
                <artifactId>druid-spring-boot-starter</artifactId>
                <version>${druid.version}</version>
            </dependency>

            <!-- mybatis-plus-->
            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>mybatis-plus-boot-starter</artifactId>
                <version>${mybatis.plus.version}</version>
            </dependency>

            <!-- page-helper -->
            <dependency>
                <groupId>com.github.pagehelper</groupId>
                <artifactId>pagehelper-spring-boot-starter</artifactId>
                <version>${pagehelper-starter}</version>
            </dependency>

            <!-- MyBatis 生成器 -->
            <dependency>
                <groupId>org.mybatis.generator</groupId>
                <artifactId>mybatis-generator-core</artifactId>
                <version>${mybatis-generator.version}</version>
            </dependency>

<!--            &lt;!&ndash; mybatis-dynamic-sql &ndash;&gt;-->
<!--            <dependency>-->
<!--                <groupId>org.mybatis.dynamic-sql</groupId>-->
<!--                <artifactId>mybatis-dynamic-sql</artifactId>-->
<!--                <version>${mybatis-dynamic-sql.version}</version>-->
<!--            </dependency>-->


            <!--JWT(Json Web Token)登录支持-->
            <dependency>
                <groupId>io.jsonwebtoken</groupId>
                <artifactId>jjwt</artifactId>
                <version>${jjwt.version}</version>
            </dependency>

            <!--MinIO JAVA SDK-->
            <dependency>
                <groupId>io.minio</groupId>
                <artifactId>minio</artifactId>
                <version>${minio.version}</version>
            </dependency>

            <!-- poi -->
            <dependency>
                <groupId>org.apache.poi</groupId>
                <artifactId>poi</artifactId>
                <version>${poi.version}</version>
            </dependency>

            <!-- poi-ooxml -->
            <dependency>
                <groupId>org.apache.poi</groupId>
                <artifactId>poi-ooxml</artifactId>
                <version>${poi-ooxml.version}</version>
            </dependency>

        </dependencies>
    </dependencyManagement>

    <build>
<!--        <plugins>-->
<!--            <plugin>-->
<!--                <groupId>org.springframework.boot</groupId>-->
<!--                <artifactId>spring-boot-maven-plugin</artifactId>-->
<!--                <version>2.2.2.RELEASE</version>-->
<!--                <configuration>-->
<!--                    <fork>true</fork>-->
<!--                    <addResources>true</addResources>-->
<!--                </configuration>-->
<!--            </plugin>-->
<!--        </plugins>-->
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-maven-plugin</artifactId>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>
</project>