jdbc.driverClass=com.mysql.jdbc.Driver
jdbc.connectionURL=jdbc:mysql://118.230.232.250:22306/program_learning_web?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
jdbc.userId=root
jdbc.password=alpl2022xufuhang

moduleName=alpl-mbg
basePackage=cn.ncepu.alpl