#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/program_learning_web?useUnicode=true&allowPublicKeyRetrieval=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
#  redis:
#    host: 192.168.111.33
#    port: 6379
#    password: alpl2022xufuhang
#minio:
#  endpoint: http://192.168.111.33:9000
#  access-key: admin
#  secret-key: alpl2022xufuhang
#  bucket-name: alpl

#自定义变量
default-host: 118.230.232.250

mysql-ip: ${default-host}
mysql-port: 22306
mysql-username: root
mysql-password: alpl2022xufuhang
#mysql-password: 123456

redis-ip: ${default-host}
redis-port: 22379
redis-password: alpl2022xufuhang
#redis-password:

minio-ip: ${default-host}
minio-port: 22900
#minio-port: 9000
minio-secret-key: alpl2022xufuhang
#minio-secret-key: xufuhang

spring:
  datasource:
    url: jdbc:mysql://${mysql-ip}:${mysql-port}/program_learning_web?useUnicode=true&allowPublicKeyRetrieval=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: ${mysql-username}
    password: ${mysql-password}
  redis:
    host: ${redis-ip}
    port: ${redis-port}
    password: ${redis-password}
minio:
  endpoint: http://${minio-ip}:${minio-port}
  access-key: admin
  secret-key: ${minio-secret-key}
  bucket-name: alpl
  avatar-bucket: avatar
server:
  port: 22001